version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/databridge-airflow
permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: codedeploy/deploy.sh
      runas: ubuntu