FROM airflow

# Sqlite only works with SequentialExecutor 
ENV AIRFLOW__CORE__EXECUTOR SequentialExecutor
ENV ENVIRONMENT TEST

WORKDIR /

# TODO: Revisit this and figure out how to avoid using root.. It seems like I'd literally have to grant access to all python directories
USER root

COPY requirements.test.txt /requirements.test.txt

# Remove the config files and move the dags and plugins where pytest can see them
RUN set -ex \
    pip3 install -r /requirements.test.txt \
    rm ${AIRFLOW_HOME}/airflow.cfg

COPY tests ${AIRFLOW_HOME}/tests
COPY scripts/run_tests.sh /run_tests.sh

RUN chmod +x /run_tests.sh

WORKDIR /${AIRFLOW_HOME}

ENTRYPOINT ["/run_tests.sh"]