version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.7.13
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=airflow
            - RABBITMQ_DEFAULT_PASS=airflow
            - RABBITMQ_DEFAULT_VHOST=airflow

    webserver:
        build:
            context: .
            dockerfile: Dockerfile.server
        image: airflow
        restart: always
        depends_on:
            - rabbitmq
        environment:
            - LOAD_EX=n
            - PROD=true
            - SEED_DB 
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: airflow
        restart: always
        depends_on:
            - webserver
        environment:
            - PROD=true
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - PROD=true
        command: scheduler

    worker:
        image: airflow
        restart: always
        depends_on:
            - webserver
        environment:
            - PROD=true
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        command: worker
